# Generated by Django 3.2.14 on 2022-12-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221211_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
