# Generated by Django 3.2.19 on 2023-05-15 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote_clip_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_image_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
